theme: jekyll-theme-midnight
collections:
  annotations:
    output: true
    permalink: /annotations/:name

defaults:
  - scope:
      path: ""
      type: "annotations"
    values:
      layout: null
