theme: jekyll-theme-midnight

collections:
  annotations:
    output: true
    permalink: /annotations/:name
    permalink: pretty
  customviews:
    output: true
    peramlink: /customviews/:path
    permalink: pretty
